// Mocks generated by Mockito 5.4.6 from annotations
// in exam_app/test/features/start_exam/data/repositories/start_exam_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:exam_app/config/base_response/base_response.dart' as _i6;
import 'package:exam_app/features/start_exam/api/api_client/start_exam_api_client.dart'
    as _i3;
import 'package:exam_app/features/start_exam/api/datasources/start_exam_local_data_source_impl.dart'
    as _i4;
import 'package:exam_app/features/start_exam/api/datasources/start_exam_remote_data_source_impl.dart'
    as _i8;
import 'package:exam_app/features/start_exam/data/models/exam_dto.dart' as _i9;
import 'package:hive/hive.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBox_0<E> extends _i1.SmartFake implements _i2.Box<E> {
  _FakeBox_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStartExamApiClient_1 extends _i1.SmartFake
    implements _i3.StartExamApiClient {
  _FakeStartExamApiClient_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [StartExamLocalDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockStartExamLocalDataSourceImpl extends _i1.Mock
    implements _i4.StartExamLocalDataSourceImpl {
  MockStartExamLocalDataSourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Box<String> get tokenBox =>
      (super.noSuchMethod(
            Invocation.getter(#tokenBox),
            returnValue: _FakeBox_0<String>(this, Invocation.getter(#tokenBox)),
          )
          as _i2.Box<String>);

  @override
  _i5.Future<_i6.BaseResponse<String>> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i5.Future<_i6.BaseResponse<String>>.value(
              _i7.dummyValue<_i6.BaseResponse<String>>(
                this,
                Invocation.method(#getToken, []),
              ),
            ),
          )
          as _i5.Future<_i6.BaseResponse<String>>);
}

/// A class which mocks [StartExamRemoteDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockStartExamRemoteDataSourceImpl extends _i1.Mock
    implements _i8.StartExamRemoteDataSourceImpl {
  MockStartExamRemoteDataSourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.StartExamApiClient get startExamApiClient =>
      (super.noSuchMethod(
            Invocation.getter(#startExamApiClient),
            returnValue: _FakeStartExamApiClient_1(
              this,
              Invocation.getter(#startExamApiClient),
            ),
          )
          as _i3.StartExamApiClient);

  @override
  _i5.Future<_i6.BaseResponse<_i9.ExamDTO>> getExamById(
    String? id,
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getExamById, [id, token]),
            returnValue: _i5.Future<_i6.BaseResponse<_i9.ExamDTO>>.value(
              _i7.dummyValue<_i6.BaseResponse<_i9.ExamDTO>>(
                this,
                Invocation.method(#getExamById, [id, token]),
              ),
            ),
          )
          as _i5.Future<_i6.BaseResponse<_i9.ExamDTO>>);
}
