// Mocks generated by Mockito 5.4.6 from annotations
// in exam_app/test/features/home/presentation/views/screens/tabs/explore_tab/data/repositories/explore_tab_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:exam_app/config/base_response/base_response.dart' as _i6;
import 'package:exam_app/features/home/presentation/views/screens/tabs/explore_tab/api/api_client/explore_tab_api_client.dart'
    as _i2;
import 'package:exam_app/features/home/presentation/views/screens/tabs/explore_tab/api/datasources/explore_tab_local_data_source_impl.dart'
    as _i9;
import 'package:exam_app/features/home/presentation/views/screens/tabs/explore_tab/api/datasources/explore_tab_remote_data_source_impl.dart'
    as _i4;
import 'package:exam_app/features/home/presentation/views/screens/tabs/explore_tab/api/datasources/get_all_exams_remote_data_source_impl.dart'
    as _i10;
import 'package:exam_app/features/home/presentation/views/screens/tabs/explore_tab/data/models/exam_dto.dart'
    as _i11;
import 'package:exam_app/features/home/presentation/views/screens/tabs/explore_tab/data/models/subject_dto.dart'
    as _i7;
import 'package:hive/hive.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeExploreTabApiClient_0 extends _i1.SmartFake
    implements _i2.ExploreTabApiClient {
  _FakeExploreTabApiClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBox_1<E> extends _i1.SmartFake implements _i3.Box<E> {
  _FakeBox_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ExploreTabRemoteDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockExploreTabRemoteDataSourceImpl extends _i1.Mock
    implements _i4.ExploreTabRemoteDataSourceImpl {
  MockExploreTabRemoteDataSourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ExploreTabApiClient get exploreTabApiClient =>
      (super.noSuchMethod(
            Invocation.getter(#exploreTabApiClient),
            returnValue: _FakeExploreTabApiClient_0(
              this,
              Invocation.getter(#exploreTabApiClient),
            ),
          )
          as _i2.ExploreTabApiClient);

  @override
  _i5.Future<_i6.BaseResponse<List<_i7.SubjectDTO>>> getAllSubjects(
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAllSubjects, [token]),
            returnValue:
                _i5.Future<_i6.BaseResponse<List<_i7.SubjectDTO>>>.value(
                  _i8.dummyValue<_i6.BaseResponse<List<_i7.SubjectDTO>>>(
                    this,
                    Invocation.method(#getAllSubjects, [token]),
                  ),
                ),
          )
          as _i5.Future<_i6.BaseResponse<List<_i7.SubjectDTO>>>);
}

/// A class which mocks [ExploreTabLocalDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockExploreTabLocalDataSourceImpl extends _i1.Mock
    implements _i9.ExploreTabLocalDataSourceImpl {
  MockExploreTabLocalDataSourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Box<String> get tokenBox =>
      (super.noSuchMethod(
            Invocation.getter(#tokenBox),
            returnValue: _FakeBox_1<String>(this, Invocation.getter(#tokenBox)),
          )
          as _i3.Box<String>);

  @override
  _i5.Future<_i6.BaseResponse<String>> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i5.Future<_i6.BaseResponse<String>>.value(
              _i8.dummyValue<_i6.BaseResponse<String>>(
                this,
                Invocation.method(#getToken, []),
              ),
            ),
          )
          as _i5.Future<_i6.BaseResponse<String>>);
}

/// A class which mocks [GetAllExamsRemoteDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllExamsRemoteDataSourceImpl extends _i1.Mock
    implements _i10.GetAllExamsRemoteDataSourceImpl {
  MockGetAllExamsRemoteDataSourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ExploreTabApiClient get exploreTabApiClient =>
      (super.noSuchMethod(
            Invocation.getter(#exploreTabApiClient),
            returnValue: _FakeExploreTabApiClient_0(
              this,
              Invocation.getter(#exploreTabApiClient),
            ),
          )
          as _i2.ExploreTabApiClient);

  @override
  _i5.Future<_i6.BaseResponse<List<_i11.ExamDTO>>> getAllExams(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getAllExams, [token]),
            returnValue: _i5.Future<_i6.BaseResponse<List<_i11.ExamDTO>>>.value(
              _i8.dummyValue<_i6.BaseResponse<List<_i11.ExamDTO>>>(
                this,
                Invocation.method(#getAllExams, [token]),
              ),
            ),
          )
          as _i5.Future<_i6.BaseResponse<List<_i11.ExamDTO>>>);
}
