// Mocks generated by Mockito 5.4.6 from annotations
// in exam_app/test/features/questions/api/data_sources/remote/get_questions_remote_data_sources_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:exam_app/features/questions/api/api_client/get_questions_api_client/questions_api_client.dart'
    as _i3;
import 'package:exam_app/features/questions/data/models/get_questions_response_model/get_questions_response_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetQuestionsResponseModel_0 extends _i1.SmartFake
    implements _i2.GetQuestionsResponseModel {
  _FakeGetQuestionsResponseModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetQuestionsApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetQuestionsApiClient extends _i1.Mock
    implements _i3.GetQuestionsApiClient {
  MockGetQuestionsApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.GetQuestionsResponseModel> getAllQuestions(
    String? examId,
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAllQuestions, [examId, token]),
            returnValue: _i4.Future<_i2.GetQuestionsResponseModel>.value(
              _FakeGetQuestionsResponseModel_0(
                this,
                Invocation.method(#getAllQuestions, [examId, token]),
              ),
            ),
          )
          as _i4.Future<_i2.GetQuestionsResponseModel>);
}
