// Mocks generated by Mockito 5.4.6 from annotations
// in exam_app/test/features/questions/data/repositories/answers_check_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:exam_app/config/base_response/base_response.dart' as _i6;
import 'package:exam_app/features/questions/api/api_client/check_answers/check_answers_api_client.dart'
    as _i2;
import 'package:exam_app/features/questions/api/data_sources/local/cache_result_local_data_source_impl.dart'
    as _i11;
import 'package:exam_app/features/questions/api/data_sources/local/get_questions_local_data_source_impl.dart'
    as _i10;
import 'package:exam_app/features/questions/api/data_sources/remote/check_answers_remote_data_source_impl.dart'
    as _i4;
import 'package:exam_app/features/questions/data/models/answers_request_model/answers_request_model.dart'
    as _i8;
import 'package:exam_app/features/questions/data/models/cached_exam_result_model/cached_exam_result_model.dart'
    as _i12;
import 'package:exam_app/features/questions/data/models/check_answers_response_model/check_answers_response_model.dart'
    as _i7;
import 'package:hive/hive.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCheckAnswersApiClient_0 extends _i1.SmartFake
    implements _i2.CheckAnswersApiClient {
  _FakeCheckAnswersApiClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBox_1<E> extends _i1.SmartFake implements _i3.Box<E> {
  _FakeBox_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CheckAnswersRemoteDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockCheckAnswersRemoteDataSourceImpl extends _i1.Mock
    implements _i4.CheckAnswersRemoteDataSourceImpl {
  MockCheckAnswersRemoteDataSourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CheckAnswersApiClient get apiClient =>
      (super.noSuchMethod(
            Invocation.getter(#apiClient),
            returnValue: _FakeCheckAnswersApiClient_0(
              this,
              Invocation.getter(#apiClient),
            ),
          )
          as _i2.CheckAnswersApiClient);

  @override
  _i5.Future<_i6.BaseResponse<_i7.CheckAnswersResponseModel>> checkAnswers({
    required _i8.AnswersRequestModel? answers,
    required String? token,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#checkAnswers, [], {
              #answers: answers,
              #token: token,
            }),
            returnValue:
                _i5.Future<
                  _i6.BaseResponse<_i7.CheckAnswersResponseModel>
                >.value(
                  _i9.dummyValue<
                    _i6.BaseResponse<_i7.CheckAnswersResponseModel>
                  >(
                    this,
                    Invocation.method(#checkAnswers, [], {
                      #answers: answers,
                      #token: token,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i6.BaseResponse<_i7.CheckAnswersResponseModel>>);
}

/// A class which mocks [GetQuestionsLocalDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetQuestionsLocalDataSourceImpl extends _i1.Mock
    implements _i10.GetQuestionsLocalDataSourceImpl {
  MockGetQuestionsLocalDataSourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Box<String> get tokenBox =>
      (super.noSuchMethod(
            Invocation.getter(#tokenBox),
            returnValue: _FakeBox_1<String>(this, Invocation.getter(#tokenBox)),
          )
          as _i3.Box<String>);

  @override
  _i6.BaseResponse<String> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i9.dummyValue<_i6.BaseResponse<String>>(
              this,
              Invocation.method(#getToken, []),
            ),
          )
          as _i6.BaseResponse<String>);
}

/// A class which mocks [CacheResultLocalDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockCacheResultLocalDataSourceImpl extends _i1.Mock
    implements _i11.CacheResultLocalDataSourceImpl {
  MockCacheResultLocalDataSourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Box<_i12.CachedExamResultModel> get cachedBox =>
      (super.noSuchMethod(
            Invocation.getter(#cachedBox),
            returnValue: _FakeBox_1<_i12.CachedExamResultModel>(
              this,
              Invocation.getter(#cachedBox),
            ),
          )
          as _i3.Box<_i12.CachedExamResultModel>);

  @override
  _i5.Future<_i6.BaseResponse<void>> cacheResult(
    _i12.CachedExamResultModel? result,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cacheResult, [result]),
            returnValue: _i5.Future<_i6.BaseResponse<void>>.value(
              _i9.dummyValue<_i6.BaseResponse<void>>(
                this,
                Invocation.method(#cacheResult, [result]),
              ),
            ),
          )
          as _i5.Future<_i6.BaseResponse<void>>);
}
