// Mocks generated by Mockito 5.4.6 from annotations
// in exam_app/test/features/questions/data/repositories/get_questions_response_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:exam_app/config/base_response/base_response.dart' as _i6;
import 'package:exam_app/features/questions/api/api_client/get_questions_api_client/questions_api_client.dart'
    as _i2;
import 'package:exam_app/features/questions/api/data_sources/local/get_questions_local_data_source_impl.dart'
    as _i9;
import 'package:exam_app/features/questions/api/data_sources/remote/get_questions_remote_data_sources_impl.dart'
    as _i4;
import 'package:exam_app/features/questions/data/models/get_questions_response_model/get_questions_response_model.dart'
    as _i7;
import 'package:hive/hive.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetQuestionsApiClient_0 extends _i1.SmartFake
    implements _i2.GetQuestionsApiClient {
  _FakeGetQuestionsApiClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBox_1<E> extends _i1.SmartFake implements _i3.Box<E> {
  _FakeBox_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetQuestionsRemoteDataSourcesImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetQuestionsRemoteDataSourcesImpl extends _i1.Mock
    implements _i4.GetQuestionsRemoteDataSourcesImpl {
  MockGetQuestionsRemoteDataSourcesImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetQuestionsApiClient get apiClient =>
      (super.noSuchMethod(
            Invocation.getter(#apiClient),
            returnValue: _FakeGetQuestionsApiClient_0(
              this,
              Invocation.getter(#apiClient),
            ),
          )
          as _i2.GetQuestionsApiClient);

  @override
  _i5.Future<_i6.BaseResponse<_i7.GetQuestionsResponseModel>> getQuestions(
    String? examId,
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getQuestions, [examId, token]),
            returnValue:
                _i5.Future<
                  _i6.BaseResponse<_i7.GetQuestionsResponseModel>
                >.value(
                  _i8.dummyValue<
                    _i6.BaseResponse<_i7.GetQuestionsResponseModel>
                  >(this, Invocation.method(#getQuestions, [examId, token])),
                ),
          )
          as _i5.Future<_i6.BaseResponse<_i7.GetQuestionsResponseModel>>);
}

/// A class which mocks [GetQuestionsLocalDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetQuestionsLocalDataSourceImpl extends _i1.Mock
    implements _i9.GetQuestionsLocalDataSourceImpl {
  MockGetQuestionsLocalDataSourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Box<String> get tokenBox =>
      (super.noSuchMethod(
            Invocation.getter(#tokenBox),
            returnValue: _FakeBox_1<String>(this, Invocation.getter(#tokenBox)),
          )
          as _i3.Box<String>);

  @override
  _i6.BaseResponse<String> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i8.dummyValue<_i6.BaseResponse<String>>(
              this,
              Invocation.method(#getToken, []),
            ),
          )
          as _i6.BaseResponse<String>);
}
