// Mocks generated by Mockito 5.4.6 from annotations
// in exam_app/test/features/start_exam/presentation/cubit/start_exam_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:exam_app/config/base_response/base_response.dart' as _i5;
import 'package:exam_app/features/start_exam/domain/entities/exam_entity.dart'
    as _i6;
import 'package:exam_app/features/start_exam/domain/repositories/start_exam_repository.dart'
    as _i2;
import 'package:exam_app/features/start_exam/domain/use_cases/start_exam_use_case.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeStartExamRepository_0 extends _i1.SmartFake
    implements _i2.StartExamRepository {
  _FakeStartExamRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [StartExamUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockStartExamUseCase extends _i1.Mock implements _i3.StartExamUseCase {
  MockStartExamUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.StartExamRepository get startExamRepository =>
      (super.noSuchMethod(
            Invocation.getter(#startExamRepository),
            returnValue: _FakeStartExamRepository_0(
              this,
              Invocation.getter(#startExamRepository),
            ),
          )
          as _i2.StartExamRepository);

  @override
  _i4.Future<_i5.BaseResponse<_i6.ExamEntity>> call(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id]),
            returnValue: _i4.Future<_i5.BaseResponse<_i6.ExamEntity>>.value(
              _i7.dummyValue<_i5.BaseResponse<_i6.ExamEntity>>(
                this,
                Invocation.method(#call, [id]),
              ),
            ),
          )
          as _i4.Future<_i5.BaseResponse<_i6.ExamEntity>>);
}
